// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	//"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Disability struct {
	ent.Schema
}

func (Disability) Fields() []ent.Field {
	return []ent.Field{
		field.Int32("id").StorageKey("DisabilityTypeID"), 
		field.String("DisabilityTypeCode"),
		field.String("DisabilityTypeDescription"),
		field.Int32("DisabilityPercentage"),
		field.Enum("DisabilityFlag").Values("Temporary", "Permanent"),}
}
func (Disability) Edges() []ent.Edge {
	//edge.To("user_disability","Employees.Type")
	return nil
}
func (Disability) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Disability"}}
}
