// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Exam_Applications_PS struct {
	ent.Schema
}

func (Exam_Applications_PS) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("id").StorageKey("ApplicationID"), 
		field.String("ApplicationNumber").Unique().Optional(),
		field.Int64("EmployeeID").Optional().Unique(),
		field.String("EmployeeName").Optional(),
		//field.Time("DOB").SchemaType(map[string]string{
		//	dialect.Postgres: "date",
		//}).Optional(),
		field.String("DOB").Optional(),
		field.Enum("Gender").Values("Male", "Female"),
		field.String("MobileNumber").Optional(),
		field.String("EmailID").Optional(),		
		field.String("EmployeeCategory").Optional(),
		field.String("Cadre").Optional(),
		field.String("EmployeePost").Optional(),
		
		field.String("FacilityID").Optional(),
		/*field.Time("DCCS").SchemaType(map[string]string{
			dialect.Postgres: "date",
		}).Optional(),
		field.Time("DCInPresentCadre").SchemaType(map[string]string{
			dialect.Postgres: "date",
		}).Optional(),*/
		field.String("DCCS").Optional(),
		field.String("DCInPresentCadre").Optional(),
		field.String("DeputationOfficeId").Optional(),
		field.String("DisabilityType").Optional(),
		field.String("DisabilityPercentage").Optional(),
		field.String("Education").Optional(),
		field.String("ExamNameCode").Optional(),
		field.String("ExamYear").Optional(),
		field.String("ExamName").Optional(),
		field.String("CentrePreference").Optional(),
		field.String("Signature").Optional(),
		field.String("Photo").Optional(),
		field.String("ApplicationStatus").Optional(),
		field.Time("ApplnSubmittedDate").SchemaType(map[string]string{
			dialect.Postgres: "date",
		}).Optional().Default(time.Now),
		field.String("VA_Remarks").Optional(),
		field.String("VA_UserName").Optional(),
		field.Time("VA_Date").SchemaType(map[string]string{
			dialect.Postgres: "date",
		}).Optional(),
		field.String("CA_Remarks").Optional(),
		field.String("CA_UserName").Optional(),
		field.Time("CA_Date").SchemaType(map[string]string{
			dialect.Postgres: "date",
		}).Optional(),
		field.Time("ApplicationWdlDate").SchemaType(map[string]string{
			dialect.Postgres: "date",
		}).Optional(),
		field.String("NA_Remarks").Optional(),
		field.String("NA_UserName").Optional(),
		field.Time("NA_Date").SchemaType(map[string]string{
			dialect.Postgres: "date",
		}).Optional(),
		field.String("AppliactionRemarks").Optional(),
		field.JSON("CadrePreferences", []interface{}{}).
		Optional(),
		field.JSON("DivisionPreferences", []interface{}{}).
		Optional(),
		field.JSON("CirclePreferences", []interface{}{}).
		Optional(),
		field.Time("UpdatedAt").SchemaType(map[string]string{
			dialect.Postgres: "date",
		}).Default(time.Now).Optional(),	
		field.String("UpdatedBy").Default("API").Optional(),
		field.Int32("RoleUserCode").Optional(),
		}
		
		
}
func (Exam_Applications_PS) Edges() []ent.Edge {
	return []ent.Edge{
		//edge.From("emps", EmployeeMaster.Type).Ref("Emp_Ref").Unique().Field("EmployeeID"),
		//edge.From("users", UserMaster.Type).Ref("Users_PS_Ref").Unique().Field("UserName"),	
		edge.To("UsersPSRef", UserMaster.Type),
		edge.To("ExamAppln_PS_Ref", Exam_PS.Type),		
		edge.To("Office_PS_Ref", Facility.Type),
		edge.From("roleusers", RoleMaster.Type).Ref("Roles_PS_Ref").Unique().Field("RoleUserCode"),
		//edge.To("CadrePref_Ref", Cadre_Choice_PS.Type),
		//edge.To("DivisionPref_Ref", Division_Choice_PS.Type),
	}

}


func (Exam_Applications_PS) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Exam_Applications_PS"}}
}
