// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"recruit/ent/cadre_choice_ps"
	"recruit/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CadreChoicePSUpdate is the builder for updating Cadre_Choice_PS entities.
type CadreChoicePSUpdate struct {
	config
	hooks    []Hook
	mutation *CadreChoicePSMutation
}

// Where appends a list predicates to the CadreChoicePSUpdate builder.
func (ccpu *CadreChoicePSUpdate) Where(ps ...predicate.Cadre_Choice_PS) *CadreChoicePSUpdate {
	ccpu.mutation.Where(ps...)
	return ccpu
}

// SetApplication sets the "Application" field.
func (ccpu *CadreChoicePSUpdate) SetApplication(s string) *CadreChoicePSUpdate {
	ccpu.mutation.SetApplication(s)
	return ccpu
}

// SetNillableApplication sets the "Application" field if the given value is not nil.
func (ccpu *CadreChoicePSUpdate) SetNillableApplication(s *string) *CadreChoicePSUpdate {
	if s != nil {
		ccpu.SetApplication(*s)
	}
	return ccpu
}

// ClearApplication clears the value of the "Application" field.
func (ccpu *CadreChoicePSUpdate) ClearApplication() *CadreChoicePSUpdate {
	ccpu.mutation.ClearApplication()
	return ccpu
}

// SetCadrePrefNo sets the "CadrePrefNo" field.
func (ccpu *CadreChoicePSUpdate) SetCadrePrefNo(s string) *CadreChoicePSUpdate {
	ccpu.mutation.SetCadrePrefNo(s)
	return ccpu
}

// SetCadrePrefValue sets the "CadrePrefValue" field.
func (ccpu *CadreChoicePSUpdate) SetCadrePrefValue(s string) *CadreChoicePSUpdate {
	ccpu.mutation.SetCadrePrefValue(s)
	return ccpu
}

// SetEmployeeID sets the "EmployeeID" field.
func (ccpu *CadreChoicePSUpdate) SetEmployeeID(i int64) *CadreChoicePSUpdate {
	ccpu.mutation.ResetEmployeeID()
	ccpu.mutation.SetEmployeeID(i)
	return ccpu
}

// SetNillableEmployeeID sets the "EmployeeID" field if the given value is not nil.
func (ccpu *CadreChoicePSUpdate) SetNillableEmployeeID(i *int64) *CadreChoicePSUpdate {
	if i != nil {
		ccpu.SetEmployeeID(*i)
	}
	return ccpu
}

// AddEmployeeID adds i to the "EmployeeID" field.
func (ccpu *CadreChoicePSUpdate) AddEmployeeID(i int64) *CadreChoicePSUpdate {
	ccpu.mutation.AddEmployeeID(i)
	return ccpu
}

// ClearEmployeeID clears the value of the "EmployeeID" field.
func (ccpu *CadreChoicePSUpdate) ClearEmployeeID() *CadreChoicePSUpdate {
	ccpu.mutation.ClearEmployeeID()
	return ccpu
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (ccpu *CadreChoicePSUpdate) SetUpdatedAt(t time.Time) *CadreChoicePSUpdate {
	ccpu.mutation.SetUpdatedAt(t)
	return ccpu
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (ccpu *CadreChoicePSUpdate) SetNillableUpdatedAt(t *time.Time) *CadreChoicePSUpdate {
	if t != nil {
		ccpu.SetUpdatedAt(*t)
	}
	return ccpu
}

// ClearUpdatedAt clears the value of the "UpdatedAt" field.
func (ccpu *CadreChoicePSUpdate) ClearUpdatedAt() *CadreChoicePSUpdate {
	ccpu.mutation.ClearUpdatedAt()
	return ccpu
}

// SetUpdatedBy sets the "UpdatedBy" field.
func (ccpu *CadreChoicePSUpdate) SetUpdatedBy(s string) *CadreChoicePSUpdate {
	ccpu.mutation.SetUpdatedBy(s)
	return ccpu
}

// SetNillableUpdatedBy sets the "UpdatedBy" field if the given value is not nil.
func (ccpu *CadreChoicePSUpdate) SetNillableUpdatedBy(s *string) *CadreChoicePSUpdate {
	if s != nil {
		ccpu.SetUpdatedBy(*s)
	}
	return ccpu
}

// ClearUpdatedBy clears the value of the "UpdatedBy" field.
func (ccpu *CadreChoicePSUpdate) ClearUpdatedBy() *CadreChoicePSUpdate {
	ccpu.mutation.ClearUpdatedBy()
	return ccpu
}

// Mutation returns the CadreChoicePSMutation object of the builder.
func (ccpu *CadreChoicePSUpdate) Mutation() *CadreChoicePSMutation {
	return ccpu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ccpu *CadreChoicePSUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ccpu.sqlSave, ccpu.mutation, ccpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ccpu *CadreChoicePSUpdate) SaveX(ctx context.Context) int {
	affected, err := ccpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ccpu *CadreChoicePSUpdate) Exec(ctx context.Context) error {
	_, err := ccpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccpu *CadreChoicePSUpdate) ExecX(ctx context.Context) {
	if err := ccpu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ccpu *CadreChoicePSUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(cadre_choice_ps.Table, cadre_choice_ps.Columns, sqlgraph.NewFieldSpec(cadre_choice_ps.FieldID, field.TypeInt32))
	if ps := ccpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ccpu.mutation.Application(); ok {
		_spec.SetField(cadre_choice_ps.FieldApplication, field.TypeString, value)
	}
	if ccpu.mutation.ApplicationCleared() {
		_spec.ClearField(cadre_choice_ps.FieldApplication, field.TypeString)
	}
	if value, ok := ccpu.mutation.CadrePrefNo(); ok {
		_spec.SetField(cadre_choice_ps.FieldCadrePrefNo, field.TypeString, value)
	}
	if value, ok := ccpu.mutation.CadrePrefValue(); ok {
		_spec.SetField(cadre_choice_ps.FieldCadrePrefValue, field.TypeString, value)
	}
	if value, ok := ccpu.mutation.EmployeeID(); ok {
		_spec.SetField(cadre_choice_ps.FieldEmployeeID, field.TypeInt64, value)
	}
	if value, ok := ccpu.mutation.AddedEmployeeID(); ok {
		_spec.AddField(cadre_choice_ps.FieldEmployeeID, field.TypeInt64, value)
	}
	if ccpu.mutation.EmployeeIDCleared() {
		_spec.ClearField(cadre_choice_ps.FieldEmployeeID, field.TypeInt64)
	}
	if value, ok := ccpu.mutation.UpdatedAt(); ok {
		_spec.SetField(cadre_choice_ps.FieldUpdatedAt, field.TypeTime, value)
	}
	if ccpu.mutation.UpdatedAtCleared() {
		_spec.ClearField(cadre_choice_ps.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := ccpu.mutation.UpdatedBy(); ok {
		_spec.SetField(cadre_choice_ps.FieldUpdatedBy, field.TypeString, value)
	}
	if ccpu.mutation.UpdatedByCleared() {
		_spec.ClearField(cadre_choice_ps.FieldUpdatedBy, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ccpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cadre_choice_ps.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ccpu.mutation.done = true
	return n, nil
}

// CadreChoicePSUpdateOne is the builder for updating a single Cadre_Choice_PS entity.
type CadreChoicePSUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CadreChoicePSMutation
}

// SetApplication sets the "Application" field.
func (ccpuo *CadreChoicePSUpdateOne) SetApplication(s string) *CadreChoicePSUpdateOne {
	ccpuo.mutation.SetApplication(s)
	return ccpuo
}

// SetNillableApplication sets the "Application" field if the given value is not nil.
func (ccpuo *CadreChoicePSUpdateOne) SetNillableApplication(s *string) *CadreChoicePSUpdateOne {
	if s != nil {
		ccpuo.SetApplication(*s)
	}
	return ccpuo
}

// ClearApplication clears the value of the "Application" field.
func (ccpuo *CadreChoicePSUpdateOne) ClearApplication() *CadreChoicePSUpdateOne {
	ccpuo.mutation.ClearApplication()
	return ccpuo
}

// SetCadrePrefNo sets the "CadrePrefNo" field.
func (ccpuo *CadreChoicePSUpdateOne) SetCadrePrefNo(s string) *CadreChoicePSUpdateOne {
	ccpuo.mutation.SetCadrePrefNo(s)
	return ccpuo
}

// SetCadrePrefValue sets the "CadrePrefValue" field.
func (ccpuo *CadreChoicePSUpdateOne) SetCadrePrefValue(s string) *CadreChoicePSUpdateOne {
	ccpuo.mutation.SetCadrePrefValue(s)
	return ccpuo
}

// SetEmployeeID sets the "EmployeeID" field.
func (ccpuo *CadreChoicePSUpdateOne) SetEmployeeID(i int64) *CadreChoicePSUpdateOne {
	ccpuo.mutation.ResetEmployeeID()
	ccpuo.mutation.SetEmployeeID(i)
	return ccpuo
}

// SetNillableEmployeeID sets the "EmployeeID" field if the given value is not nil.
func (ccpuo *CadreChoicePSUpdateOne) SetNillableEmployeeID(i *int64) *CadreChoicePSUpdateOne {
	if i != nil {
		ccpuo.SetEmployeeID(*i)
	}
	return ccpuo
}

// AddEmployeeID adds i to the "EmployeeID" field.
func (ccpuo *CadreChoicePSUpdateOne) AddEmployeeID(i int64) *CadreChoicePSUpdateOne {
	ccpuo.mutation.AddEmployeeID(i)
	return ccpuo
}

// ClearEmployeeID clears the value of the "EmployeeID" field.
func (ccpuo *CadreChoicePSUpdateOne) ClearEmployeeID() *CadreChoicePSUpdateOne {
	ccpuo.mutation.ClearEmployeeID()
	return ccpuo
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (ccpuo *CadreChoicePSUpdateOne) SetUpdatedAt(t time.Time) *CadreChoicePSUpdateOne {
	ccpuo.mutation.SetUpdatedAt(t)
	return ccpuo
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (ccpuo *CadreChoicePSUpdateOne) SetNillableUpdatedAt(t *time.Time) *CadreChoicePSUpdateOne {
	if t != nil {
		ccpuo.SetUpdatedAt(*t)
	}
	return ccpuo
}

// ClearUpdatedAt clears the value of the "UpdatedAt" field.
func (ccpuo *CadreChoicePSUpdateOne) ClearUpdatedAt() *CadreChoicePSUpdateOne {
	ccpuo.mutation.ClearUpdatedAt()
	return ccpuo
}

// SetUpdatedBy sets the "UpdatedBy" field.
func (ccpuo *CadreChoicePSUpdateOne) SetUpdatedBy(s string) *CadreChoicePSUpdateOne {
	ccpuo.mutation.SetUpdatedBy(s)
	return ccpuo
}

// SetNillableUpdatedBy sets the "UpdatedBy" field if the given value is not nil.
func (ccpuo *CadreChoicePSUpdateOne) SetNillableUpdatedBy(s *string) *CadreChoicePSUpdateOne {
	if s != nil {
		ccpuo.SetUpdatedBy(*s)
	}
	return ccpuo
}

// ClearUpdatedBy clears the value of the "UpdatedBy" field.
func (ccpuo *CadreChoicePSUpdateOne) ClearUpdatedBy() *CadreChoicePSUpdateOne {
	ccpuo.mutation.ClearUpdatedBy()
	return ccpuo
}

// Mutation returns the CadreChoicePSMutation object of the builder.
func (ccpuo *CadreChoicePSUpdateOne) Mutation() *CadreChoicePSMutation {
	return ccpuo.mutation
}

// Where appends a list predicates to the CadreChoicePSUpdate builder.
func (ccpuo *CadreChoicePSUpdateOne) Where(ps ...predicate.Cadre_Choice_PS) *CadreChoicePSUpdateOne {
	ccpuo.mutation.Where(ps...)
	return ccpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ccpuo *CadreChoicePSUpdateOne) Select(field string, fields ...string) *CadreChoicePSUpdateOne {
	ccpuo.fields = append([]string{field}, fields...)
	return ccpuo
}

// Save executes the query and returns the updated Cadre_Choice_PS entity.
func (ccpuo *CadreChoicePSUpdateOne) Save(ctx context.Context) (*Cadre_Choice_PS, error) {
	return withHooks(ctx, ccpuo.sqlSave, ccpuo.mutation, ccpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ccpuo *CadreChoicePSUpdateOne) SaveX(ctx context.Context) *Cadre_Choice_PS {
	node, err := ccpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ccpuo *CadreChoicePSUpdateOne) Exec(ctx context.Context) error {
	_, err := ccpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccpuo *CadreChoicePSUpdateOne) ExecX(ctx context.Context) {
	if err := ccpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ccpuo *CadreChoicePSUpdateOne) sqlSave(ctx context.Context) (_node *Cadre_Choice_PS, err error) {
	_spec := sqlgraph.NewUpdateSpec(cadre_choice_ps.Table, cadre_choice_ps.Columns, sqlgraph.NewFieldSpec(cadre_choice_ps.FieldID, field.TypeInt32))
	id, ok := ccpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Cadre_Choice_PS.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ccpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cadre_choice_ps.FieldID)
		for _, f := range fields {
			if !cadre_choice_ps.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cadre_choice_ps.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ccpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ccpuo.mutation.Application(); ok {
		_spec.SetField(cadre_choice_ps.FieldApplication, field.TypeString, value)
	}
	if ccpuo.mutation.ApplicationCleared() {
		_spec.ClearField(cadre_choice_ps.FieldApplication, field.TypeString)
	}
	if value, ok := ccpuo.mutation.CadrePrefNo(); ok {
		_spec.SetField(cadre_choice_ps.FieldCadrePrefNo, field.TypeString, value)
	}
	if value, ok := ccpuo.mutation.CadrePrefValue(); ok {
		_spec.SetField(cadre_choice_ps.FieldCadrePrefValue, field.TypeString, value)
	}
	if value, ok := ccpuo.mutation.EmployeeID(); ok {
		_spec.SetField(cadre_choice_ps.FieldEmployeeID, field.TypeInt64, value)
	}
	if value, ok := ccpuo.mutation.AddedEmployeeID(); ok {
		_spec.AddField(cadre_choice_ps.FieldEmployeeID, field.TypeInt64, value)
	}
	if ccpuo.mutation.EmployeeIDCleared() {
		_spec.ClearField(cadre_choice_ps.FieldEmployeeID, field.TypeInt64)
	}
	if value, ok := ccpuo.mutation.UpdatedAt(); ok {
		_spec.SetField(cadre_choice_ps.FieldUpdatedAt, field.TypeTime, value)
	}
	if ccpuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(cadre_choice_ps.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := ccpuo.mutation.UpdatedBy(); ok {
		_spec.SetField(cadre_choice_ps.FieldUpdatedBy, field.TypeString, value)
	}
	if ccpuo.mutation.UpdatedByCleared() {
		_spec.ClearField(cadre_choice_ps.FieldUpdatedBy, field.TypeString)
	}
	_node = &Cadre_Choice_PS{config: ccpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ccpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cadre_choice_ps.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ccpuo.mutation.done = true
	return _node, nil
}
