// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"recruit/ent/circlemaster"
	"recruit/ent/facility"
	"recruit/ent/predicate"
	"recruit/ent/regionmaster"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CircleMasterQuery is the builder for querying CircleMaster entities.
type CircleMasterQuery struct {
	config
	ctx           *QueryContext
	order         []circlemaster.OrderOption
	inters        []Interceptor
	predicates    []predicate.CircleMaster
	withRegionRef *RegionMasterQuery
	withCircleRef *FacilityQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CircleMasterQuery builder.
func (cmq *CircleMasterQuery) Where(ps ...predicate.CircleMaster) *CircleMasterQuery {
	cmq.predicates = append(cmq.predicates, ps...)
	return cmq
}

// Limit the number of records to be returned by this query.
func (cmq *CircleMasterQuery) Limit(limit int) *CircleMasterQuery {
	cmq.ctx.Limit = &limit
	return cmq
}

// Offset to start from.
func (cmq *CircleMasterQuery) Offset(offset int) *CircleMasterQuery {
	cmq.ctx.Offset = &offset
	return cmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cmq *CircleMasterQuery) Unique(unique bool) *CircleMasterQuery {
	cmq.ctx.Unique = &unique
	return cmq
}

// Order specifies how the records should be ordered.
func (cmq *CircleMasterQuery) Order(o ...circlemaster.OrderOption) *CircleMasterQuery {
	cmq.order = append(cmq.order, o...)
	return cmq
}

// QueryRegionRef chains the current query on the "region_ref" edge.
func (cmq *CircleMasterQuery) QueryRegionRef() *RegionMasterQuery {
	query := (&RegionMasterClient{config: cmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(circlemaster.Table, circlemaster.FieldID, selector),
			sqlgraph.To(regionmaster.Table, regionmaster.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, circlemaster.RegionRefTable, circlemaster.RegionRefColumn),
		)
		fromU = sqlgraph.SetNeighbors(cmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCircleRef chains the current query on the "circle_ref" edge.
func (cmq *CircleMasterQuery) QueryCircleRef() *FacilityQuery {
	query := (&FacilityClient{config: cmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(circlemaster.Table, circlemaster.FieldID, selector),
			sqlgraph.To(facility.Table, facility.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, circlemaster.CircleRefTable, circlemaster.CircleRefColumn),
		)
		fromU = sqlgraph.SetNeighbors(cmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CircleMaster entity from the query.
// Returns a *NotFoundError when no CircleMaster was found.
func (cmq *CircleMasterQuery) First(ctx context.Context) (*CircleMaster, error) {
	nodes, err := cmq.Limit(1).All(setContextOp(ctx, cmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{circlemaster.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cmq *CircleMasterQuery) FirstX(ctx context.Context) *CircleMaster {
	node, err := cmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CircleMaster ID from the query.
// Returns a *NotFoundError when no CircleMaster ID was found.
func (cmq *CircleMasterQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = cmq.Limit(1).IDs(setContextOp(ctx, cmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{circlemaster.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cmq *CircleMasterQuery) FirstIDX(ctx context.Context) int32 {
	id, err := cmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CircleMaster entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CircleMaster entity is found.
// Returns a *NotFoundError when no CircleMaster entities are found.
func (cmq *CircleMasterQuery) Only(ctx context.Context) (*CircleMaster, error) {
	nodes, err := cmq.Limit(2).All(setContextOp(ctx, cmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{circlemaster.Label}
	default:
		return nil, &NotSingularError{circlemaster.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cmq *CircleMasterQuery) OnlyX(ctx context.Context) *CircleMaster {
	node, err := cmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CircleMaster ID in the query.
// Returns a *NotSingularError when more than one CircleMaster ID is found.
// Returns a *NotFoundError when no entities are found.
func (cmq *CircleMasterQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = cmq.Limit(2).IDs(setContextOp(ctx, cmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{circlemaster.Label}
	default:
		err = &NotSingularError{circlemaster.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cmq *CircleMasterQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := cmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CircleMasters.
func (cmq *CircleMasterQuery) All(ctx context.Context) ([]*CircleMaster, error) {
	ctx = setContextOp(ctx, cmq.ctx, "All")
	if err := cmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CircleMaster, *CircleMasterQuery]()
	return withInterceptors[[]*CircleMaster](ctx, cmq, qr, cmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cmq *CircleMasterQuery) AllX(ctx context.Context) []*CircleMaster {
	nodes, err := cmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CircleMaster IDs.
func (cmq *CircleMasterQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if cmq.ctx.Unique == nil && cmq.path != nil {
		cmq.Unique(true)
	}
	ctx = setContextOp(ctx, cmq.ctx, "IDs")
	if err = cmq.Select(circlemaster.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cmq *CircleMasterQuery) IDsX(ctx context.Context) []int32 {
	ids, err := cmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cmq *CircleMasterQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cmq.ctx, "Count")
	if err := cmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cmq, querierCount[*CircleMasterQuery](), cmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cmq *CircleMasterQuery) CountX(ctx context.Context) int {
	count, err := cmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cmq *CircleMasterQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cmq.ctx, "Exist")
	switch _, err := cmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cmq *CircleMasterQuery) ExistX(ctx context.Context) bool {
	exist, err := cmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CircleMasterQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cmq *CircleMasterQuery) Clone() *CircleMasterQuery {
	if cmq == nil {
		return nil
	}
	return &CircleMasterQuery{
		config:        cmq.config,
		ctx:           cmq.ctx.Clone(),
		order:         append([]circlemaster.OrderOption{}, cmq.order...),
		inters:        append([]Interceptor{}, cmq.inters...),
		predicates:    append([]predicate.CircleMaster{}, cmq.predicates...),
		withRegionRef: cmq.withRegionRef.Clone(),
		withCircleRef: cmq.withCircleRef.Clone(),
		// clone intermediate query.
		sql:  cmq.sql.Clone(),
		path: cmq.path,
	}
}

// WithRegionRef tells the query-builder to eager-load the nodes that are connected to
// the "region_ref" edge. The optional arguments are used to configure the query builder of the edge.
func (cmq *CircleMasterQuery) WithRegionRef(opts ...func(*RegionMasterQuery)) *CircleMasterQuery {
	query := (&RegionMasterClient{config: cmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cmq.withRegionRef = query
	return cmq
}

// WithCircleRef tells the query-builder to eager-load the nodes that are connected to
// the "circle_ref" edge. The optional arguments are used to configure the query builder of the edge.
func (cmq *CircleMasterQuery) WithCircleRef(opts ...func(*FacilityQuery)) *CircleMasterQuery {
	query := (&FacilityClient{config: cmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cmq.withCircleRef = query
	return cmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CircleCode int32 `json:"CircleCode,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CircleMaster.Query().
//		GroupBy(circlemaster.FieldCircleCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cmq *CircleMasterQuery) GroupBy(field string, fields ...string) *CircleMasterGroupBy {
	cmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CircleMasterGroupBy{build: cmq}
	grbuild.flds = &cmq.ctx.Fields
	grbuild.label = circlemaster.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CircleCode int32 `json:"CircleCode,omitempty"`
//	}
//
//	client.CircleMaster.Query().
//		Select(circlemaster.FieldCircleCode).
//		Scan(ctx, &v)
func (cmq *CircleMasterQuery) Select(fields ...string) *CircleMasterSelect {
	cmq.ctx.Fields = append(cmq.ctx.Fields, fields...)
	sbuild := &CircleMasterSelect{CircleMasterQuery: cmq}
	sbuild.label = circlemaster.Label
	sbuild.flds, sbuild.scan = &cmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CircleMasterSelect configured with the given aggregations.
func (cmq *CircleMasterQuery) Aggregate(fns ...AggregateFunc) *CircleMasterSelect {
	return cmq.Select().Aggregate(fns...)
}

func (cmq *CircleMasterQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cmq); err != nil {
				return err
			}
		}
	}
	for _, f := range cmq.ctx.Fields {
		if !circlemaster.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cmq.path != nil {
		prev, err := cmq.path(ctx)
		if err != nil {
			return err
		}
		cmq.sql = prev
	}
	return nil
}

func (cmq *CircleMasterQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CircleMaster, error) {
	var (
		nodes       = []*CircleMaster{}
		withFKs     = cmq.withFKs
		_spec       = cmq.querySpec()
		loadedTypes = [2]bool{
			cmq.withRegionRef != nil,
			cmq.withCircleRef != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, circlemaster.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CircleMaster).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CircleMaster{config: cmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cmq.withRegionRef; query != nil {
		if err := cmq.loadRegionRef(ctx, query, nodes,
			func(n *CircleMaster) { n.Edges.RegionRef = []*RegionMaster{} },
			func(n *CircleMaster, e *RegionMaster) { n.Edges.RegionRef = append(n.Edges.RegionRef, e) }); err != nil {
			return nil, err
		}
	}
	if query := cmq.withCircleRef; query != nil {
		if err := cmq.loadCircleRef(ctx, query, nodes,
			func(n *CircleMaster) { n.Edges.CircleRef = []*Facility{} },
			func(n *CircleMaster, e *Facility) { n.Edges.CircleRef = append(n.Edges.CircleRef, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cmq *CircleMasterQuery) loadRegionRef(ctx context.Context, query *RegionMasterQuery, nodes []*CircleMaster, init func(*CircleMaster), assign func(*CircleMaster, *RegionMaster)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int32]*CircleMaster)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.RegionMaster(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(circlemaster.RegionRefColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.circle_master_region_ref
		if fk == nil {
			return fmt.Errorf(`foreign-key "circle_master_region_ref" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "circle_master_region_ref" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cmq *CircleMasterQuery) loadCircleRef(ctx context.Context, query *FacilityQuery, nodes []*CircleMaster, init func(*CircleMaster), assign func(*CircleMaster, *Facility)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int32]*CircleMaster)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Facility(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(circlemaster.CircleRefColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.circle_master_circle_ref
		if fk == nil {
			return fmt.Errorf(`foreign-key "circle_master_circle_ref" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "circle_master_circle_ref" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cmq *CircleMasterQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cmq.querySpec()
	_spec.Node.Columns = cmq.ctx.Fields
	if len(cmq.ctx.Fields) > 0 {
		_spec.Unique = cmq.ctx.Unique != nil && *cmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cmq.driver, _spec)
}

func (cmq *CircleMasterQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(circlemaster.Table, circlemaster.Columns, sqlgraph.NewFieldSpec(circlemaster.FieldID, field.TypeInt32))
	_spec.From = cmq.sql
	if unique := cmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cmq.path != nil {
		_spec.Unique = true
	}
	if fields := cmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, circlemaster.FieldID)
		for i := range fields {
			if fields[i] != circlemaster.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cmq *CircleMasterQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cmq.driver.Dialect())
	t1 := builder.Table(circlemaster.Table)
	columns := cmq.ctx.Fields
	if len(columns) == 0 {
		columns = circlemaster.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cmq.sql != nil {
		selector = cmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cmq.ctx.Unique != nil && *cmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cmq.predicates {
		p(selector)
	}
	for _, p := range cmq.order {
		p(selector)
	}
	if offset := cmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CircleMasterGroupBy is the group-by builder for CircleMaster entities.
type CircleMasterGroupBy struct {
	selector
	build *CircleMasterQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cmgb *CircleMasterGroupBy) Aggregate(fns ...AggregateFunc) *CircleMasterGroupBy {
	cmgb.fns = append(cmgb.fns, fns...)
	return cmgb
}

// Scan applies the selector query and scans the result into the given value.
func (cmgb *CircleMasterGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cmgb.build.ctx, "GroupBy")
	if err := cmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CircleMasterQuery, *CircleMasterGroupBy](ctx, cmgb.build, cmgb, cmgb.build.inters, v)
}

func (cmgb *CircleMasterGroupBy) sqlScan(ctx context.Context, root *CircleMasterQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cmgb.fns))
	for _, fn := range cmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cmgb.flds)+len(cmgb.fns))
		for _, f := range *cmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CircleMasterSelect is the builder for selecting fields of CircleMaster entities.
type CircleMasterSelect struct {
	*CircleMasterQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cms *CircleMasterSelect) Aggregate(fns ...AggregateFunc) *CircleMasterSelect {
	cms.fns = append(cms.fns, fns...)
	return cms
}

// Scan applies the selector query and scans the result into the given value.
func (cms *CircleMasterSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cms.ctx, "Select")
	if err := cms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CircleMasterQuery, *CircleMasterSelect](ctx, cms.CircleMasterQuery, cms, cms.inters, v)
}

func (cms *CircleMasterSelect) sqlScan(ctx context.Context, root *CircleMasterQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cms.fns))
	for _, fn := range cms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
