// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"recruit/ent/division_choice_pm"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DivisionChoicePMCreate is the builder for creating a Division_Choice_PM entity.
type DivisionChoicePMCreate struct {
	config
	mutation *DivisionChoicePMMutation
	hooks    []Hook
}

// SetApplication sets the "Application" field.
func (dcpc *DivisionChoicePMCreate) SetApplication(s string) *DivisionChoicePMCreate {
	dcpc.mutation.SetApplication(s)
	return dcpc
}

// SetNillableApplication sets the "Application" field if the given value is not nil.
func (dcpc *DivisionChoicePMCreate) SetNillableApplication(s *string) *DivisionChoicePMCreate {
	if s != nil {
		dcpc.SetApplication(*s)
	}
	return dcpc
}

// SetCadrePrefNo sets the "CadrePrefNo" field.
func (dcpc *DivisionChoicePMCreate) SetCadrePrefNo(s string) *DivisionChoicePMCreate {
	dcpc.mutation.SetCadrePrefNo(s)
	return dcpc
}

// SetCadrePrefValue sets the "CadrePrefValue" field.
func (dcpc *DivisionChoicePMCreate) SetCadrePrefValue(s string) *DivisionChoicePMCreate {
	dcpc.mutation.SetCadrePrefValue(s)
	return dcpc
}

// SetEmployeeID sets the "EmployeeID" field.
func (dcpc *DivisionChoicePMCreate) SetEmployeeID(i int64) *DivisionChoicePMCreate {
	dcpc.mutation.SetEmployeeID(i)
	return dcpc
}

// SetNillableEmployeeID sets the "EmployeeID" field if the given value is not nil.
func (dcpc *DivisionChoicePMCreate) SetNillableEmployeeID(i *int64) *DivisionChoicePMCreate {
	if i != nil {
		dcpc.SetEmployeeID(*i)
	}
	return dcpc
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (dcpc *DivisionChoicePMCreate) SetUpdatedAt(t time.Time) *DivisionChoicePMCreate {
	dcpc.mutation.SetUpdatedAt(t)
	return dcpc
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (dcpc *DivisionChoicePMCreate) SetNillableUpdatedAt(t *time.Time) *DivisionChoicePMCreate {
	if t != nil {
		dcpc.SetUpdatedAt(*t)
	}
	return dcpc
}

// SetUpdatedBy sets the "UpdatedBy" field.
func (dcpc *DivisionChoicePMCreate) SetUpdatedBy(s string) *DivisionChoicePMCreate {
	dcpc.mutation.SetUpdatedBy(s)
	return dcpc
}

// SetNillableUpdatedBy sets the "UpdatedBy" field if the given value is not nil.
func (dcpc *DivisionChoicePMCreate) SetNillableUpdatedBy(s *string) *DivisionChoicePMCreate {
	if s != nil {
		dcpc.SetUpdatedBy(*s)
	}
	return dcpc
}

// SetID sets the "id" field.
func (dcpc *DivisionChoicePMCreate) SetID(i int32) *DivisionChoicePMCreate {
	dcpc.mutation.SetID(i)
	return dcpc
}

// Mutation returns the DivisionChoicePMMutation object of the builder.
func (dcpc *DivisionChoicePMCreate) Mutation() *DivisionChoicePMMutation {
	return dcpc.mutation
}

// Save creates the Division_Choice_PM in the database.
func (dcpc *DivisionChoicePMCreate) Save(ctx context.Context) (*Division_Choice_PM, error) {
	dcpc.defaults()
	return withHooks(ctx, dcpc.sqlSave, dcpc.mutation, dcpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dcpc *DivisionChoicePMCreate) SaveX(ctx context.Context) *Division_Choice_PM {
	v, err := dcpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcpc *DivisionChoicePMCreate) Exec(ctx context.Context) error {
	_, err := dcpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcpc *DivisionChoicePMCreate) ExecX(ctx context.Context) {
	if err := dcpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dcpc *DivisionChoicePMCreate) defaults() {
	if _, ok := dcpc.mutation.UpdatedAt(); !ok {
		v := division_choice_pm.DefaultUpdatedAt()
		dcpc.mutation.SetUpdatedAt(v)
	}
	if _, ok := dcpc.mutation.UpdatedBy(); !ok {
		v := division_choice_pm.DefaultUpdatedBy
		dcpc.mutation.SetUpdatedBy(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dcpc *DivisionChoicePMCreate) check() error {
	if _, ok := dcpc.mutation.CadrePrefNo(); !ok {
		return &ValidationError{Name: "CadrePrefNo", err: errors.New(`ent: missing required field "Division_Choice_PM.CadrePrefNo"`)}
	}
	if _, ok := dcpc.mutation.CadrePrefValue(); !ok {
		return &ValidationError{Name: "CadrePrefValue", err: errors.New(`ent: missing required field "Division_Choice_PM.CadrePrefValue"`)}
	}
	return nil
}

func (dcpc *DivisionChoicePMCreate) sqlSave(ctx context.Context) (*Division_Choice_PM, error) {
	if err := dcpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dcpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dcpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int32(id)
	}
	dcpc.mutation.id = &_node.ID
	dcpc.mutation.done = true
	return _node, nil
}

func (dcpc *DivisionChoicePMCreate) createSpec() (*Division_Choice_PM, *sqlgraph.CreateSpec) {
	var (
		_node = &Division_Choice_PM{config: dcpc.config}
		_spec = sqlgraph.NewCreateSpec(division_choice_pm.Table, sqlgraph.NewFieldSpec(division_choice_pm.FieldID, field.TypeInt32))
	)
	if id, ok := dcpc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dcpc.mutation.Application(); ok {
		_spec.SetField(division_choice_pm.FieldApplication, field.TypeString, value)
		_node.Application = value
	}
	if value, ok := dcpc.mutation.CadrePrefNo(); ok {
		_spec.SetField(division_choice_pm.FieldCadrePrefNo, field.TypeString, value)
		_node.CadrePrefNo = value
	}
	if value, ok := dcpc.mutation.CadrePrefValue(); ok {
		_spec.SetField(division_choice_pm.FieldCadrePrefValue, field.TypeString, value)
		_node.CadrePrefValue = value
	}
	if value, ok := dcpc.mutation.EmployeeID(); ok {
		_spec.SetField(division_choice_pm.FieldEmployeeID, field.TypeInt64, value)
		_node.EmployeeID = value
	}
	if value, ok := dcpc.mutation.UpdatedAt(); ok {
		_spec.SetField(division_choice_pm.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := dcpc.mutation.UpdatedBy(); ok {
		_spec.SetField(division_choice_pm.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	return _node, _spec
}

// DivisionChoicePMCreateBulk is the builder for creating many Division_Choice_PM entities in bulk.
type DivisionChoicePMCreateBulk struct {
	config
	builders []*DivisionChoicePMCreate
}

// Save creates the Division_Choice_PM entities in the database.
func (dcpcb *DivisionChoicePMCreateBulk) Save(ctx context.Context) ([]*Division_Choice_PM, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcpcb.builders))
	nodes := make([]*Division_Choice_PM, len(dcpcb.builders))
	mutators := make([]Mutator, len(dcpcb.builders))
	for i := range dcpcb.builders {
		func(i int, root context.Context) {
			builder := dcpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DivisionChoicePMMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcpcb *DivisionChoicePMCreateBulk) SaveX(ctx context.Context) []*Division_Choice_PM {
	v, err := dcpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcpcb *DivisionChoicePMCreateBulk) Exec(ctx context.Context) error {
	_, err := dcpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcpcb *DivisionChoicePMCreateBulk) ExecX(ctx context.Context) {
	if err := dcpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
