// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"recruit/ent/divisionmaster"
	"recruit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DivisionMasterDelete is the builder for deleting a DivisionMaster entity.
type DivisionMasterDelete struct {
	config
	hooks    []Hook
	mutation *DivisionMasterMutation
}

// Where appends a list predicates to the DivisionMasterDelete builder.
func (dmd *DivisionMasterDelete) Where(ps ...predicate.DivisionMaster) *DivisionMasterDelete {
	dmd.mutation.Where(ps...)
	return dmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dmd *DivisionMasterDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dmd.sqlExec, dmd.mutation, dmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dmd *DivisionMasterDelete) ExecX(ctx context.Context) int {
	n, err := dmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dmd *DivisionMasterDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(divisionmaster.Table, sqlgraph.NewFieldSpec(divisionmaster.FieldID, field.TypeInt32))
	if ps := dmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dmd.mutation.done = true
	return affected, err
}

// DivisionMasterDeleteOne is the builder for deleting a single DivisionMaster entity.
type DivisionMasterDeleteOne struct {
	dmd *DivisionMasterDelete
}

// Where appends a list predicates to the DivisionMasterDelete builder.
func (dmdo *DivisionMasterDeleteOne) Where(ps ...predicate.DivisionMaster) *DivisionMasterDeleteOne {
	dmdo.dmd.mutation.Where(ps...)
	return dmdo
}

// Exec executes the deletion query.
func (dmdo *DivisionMasterDeleteOne) Exec(ctx context.Context) error {
	n, err := dmdo.dmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{divisionmaster.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dmdo *DivisionMasterDeleteOne) ExecX(ctx context.Context) {
	if err := dmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
