// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"recruit/ent/employeemaster"
	"recruit/ent/exam_applications_ps"
	"recruit/ent/usermaster"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmployeeMasterCreate is the builder for creating a EmployeeMaster entity.
type EmployeeMasterCreate struct {
	config
	mutation *EmployeeMasterMutation
	hooks    []Hook
}

// SetEmployeeID sets the "EmployeeID" field.
func (emc *EmployeeMasterCreate) SetEmployeeID(i int64) *EmployeeMasterCreate {
	emc.mutation.SetEmployeeID(i)
	return emc
}

// SetEmployeeName sets the "EmployeeName" field.
func (emc *EmployeeMasterCreate) SetEmployeeName(s string) *EmployeeMasterCreate {
	emc.mutation.SetEmployeeName(s)
	return emc
}

// SetNillableEmployeeName sets the "EmployeeName" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableEmployeeName(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetEmployeeName(*s)
	}
	return emc
}

// SetDOB sets the "DOB" field.
func (emc *EmployeeMasterCreate) SetDOB(s string) *EmployeeMasterCreate {
	emc.mutation.SetDOB(s)
	return emc
}

// SetNillableDOB sets the "DOB" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableDOB(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetDOB(*s)
	}
	return emc
}

// SetGender sets the "Gender" field.
func (emc *EmployeeMasterCreate) SetGender(e employeemaster.Gender) *EmployeeMasterCreate {
	emc.mutation.SetGender(e)
	return emc
}

// SetMobileNumber sets the "MobileNumber" field.
func (emc *EmployeeMasterCreate) SetMobileNumber(s string) *EmployeeMasterCreate {
	emc.mutation.SetMobileNumber(s)
	return emc
}

// SetNillableMobileNumber sets the "MobileNumber" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableMobileNumber(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetMobileNumber(*s)
	}
	return emc
}

// SetEmailID sets the "EmailID" field.
func (emc *EmployeeMasterCreate) SetEmailID(s string) *EmployeeMasterCreate {
	emc.mutation.SetEmailID(s)
	return emc
}

// SetNillableEmailID sets the "EmailID" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableEmailID(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetEmailID(*s)
	}
	return emc
}

// SetEmployeeCategoryCode sets the "EmployeeCategoryCode" field.
func (emc *EmployeeMasterCreate) SetEmployeeCategoryCode(s string) *EmployeeMasterCreate {
	emc.mutation.SetEmployeeCategoryCode(s)
	return emc
}

// SetNillableEmployeeCategoryCode sets the "EmployeeCategoryCode" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableEmployeeCategoryCode(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetEmployeeCategoryCode(*s)
	}
	return emc
}

// SetEmployeeCategory sets the "EmployeeCategory" field.
func (emc *EmployeeMasterCreate) SetEmployeeCategory(s string) *EmployeeMasterCreate {
	emc.mutation.SetEmployeeCategory(s)
	return emc
}

// SetNillableEmployeeCategory sets the "EmployeeCategory" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableEmployeeCategory(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetEmployeeCategory(*s)
	}
	return emc
}

// SetPostCode sets the "PostCode" field.
func (emc *EmployeeMasterCreate) SetPostCode(s string) *EmployeeMasterCreate {
	emc.mutation.SetPostCode(s)
	return emc
}

// SetNillablePostCode sets the "PostCode" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillablePostCode(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetPostCode(*s)
	}
	return emc
}

// SetEmployeePost sets the "EmployeePost" field.
func (emc *EmployeeMasterCreate) SetEmployeePost(s string) *EmployeeMasterCreate {
	emc.mutation.SetEmployeePost(s)
	return emc
}

// SetNillableEmployeePost sets the "EmployeePost" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableEmployeePost(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetEmployeePost(*s)
	}
	return emc
}

// SetFacilityID sets the "FacilityID" field.
func (emc *EmployeeMasterCreate) SetFacilityID(s string) *EmployeeMasterCreate {
	emc.mutation.SetFacilityID(s)
	return emc
}

// SetNillableFacilityID sets the "FacilityID" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableFacilityID(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetFacilityID(*s)
	}
	return emc
}

// SetDCCS sets the "DCCS" field.
func (emc *EmployeeMasterCreate) SetDCCS(s string) *EmployeeMasterCreate {
	emc.mutation.SetDCCS(s)
	return emc
}

// SetNillableDCCS sets the "DCCS" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableDCCS(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetDCCS(*s)
	}
	return emc
}

// SetDCInPresentCadre sets the "DCInPresentCadre" field.
func (emc *EmployeeMasterCreate) SetDCInPresentCadre(s string) *EmployeeMasterCreate {
	emc.mutation.SetDCInPresentCadre(s)
	return emc
}

// SetNillableDCInPresentCadre sets the "DCInPresentCadre" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableDCInPresentCadre(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetDCInPresentCadre(*s)
	}
	return emc
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (emc *EmployeeMasterCreate) SetUpdatedAt(t time.Time) *EmployeeMasterCreate {
	emc.mutation.SetUpdatedAt(t)
	return emc
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableUpdatedAt(t *time.Time) *EmployeeMasterCreate {
	if t != nil {
		emc.SetUpdatedAt(*t)
	}
	return emc
}

// SetUpdatedBy sets the "UpdatedBy" field.
func (emc *EmployeeMasterCreate) SetUpdatedBy(s string) *EmployeeMasterCreate {
	emc.mutation.SetUpdatedBy(s)
	return emc
}

// SetNillableUpdatedBy sets the "UpdatedBy" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableUpdatedBy(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetUpdatedBy(*s)
	}
	return emc
}

// SetCadre sets the "Cadre" field.
func (emc *EmployeeMasterCreate) SetCadre(s string) *EmployeeMasterCreate {
	emc.mutation.SetCadre(s)
	return emc
}

// SetNillableCadre sets the "Cadre" field if the given value is not nil.
func (emc *EmployeeMasterCreate) SetNillableCadre(s *string) *EmployeeMasterCreate {
	if s != nil {
		emc.SetCadre(*s)
	}
	return emc
}

// SetID sets the "id" field.
func (emc *EmployeeMasterCreate) SetID(i int64) *EmployeeMasterCreate {
	emc.mutation.SetID(i)
	return emc
}

// AddUsermasterRefIDs adds the "UsermasterRef" edge to the UserMaster entity by IDs.
func (emc *EmployeeMasterCreate) AddUsermasterRefIDs(ids ...int64) *EmployeeMasterCreate {
	emc.mutation.AddUsermasterRefIDs(ids...)
	return emc
}

// AddUsermasterRef adds the "UsermasterRef" edges to the UserMaster entity.
func (emc *EmployeeMasterCreate) AddUsermasterRef(u ...*UserMaster) *EmployeeMasterCreate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return emc.AddUsermasterRefIDs(ids...)
}

// AddEmpRefIDs adds the "Emp_Ref" edge to the Exam_Applications_PS entity by IDs.
func (emc *EmployeeMasterCreate) AddEmpRefIDs(ids ...int64) *EmployeeMasterCreate {
	emc.mutation.AddEmpRefIDs(ids...)
	return emc
}

// AddEmpRef adds the "Emp_Ref" edges to the Exam_Applications_PS entity.
func (emc *EmployeeMasterCreate) AddEmpRef(e ...*Exam_Applications_PS) *EmployeeMasterCreate {
	ids := make([]int64, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return emc.AddEmpRefIDs(ids...)
}

// Mutation returns the EmployeeMasterMutation object of the builder.
func (emc *EmployeeMasterCreate) Mutation() *EmployeeMasterMutation {
	return emc.mutation
}

// Save creates the EmployeeMaster in the database.
func (emc *EmployeeMasterCreate) Save(ctx context.Context) (*EmployeeMaster, error) {
	emc.defaults()
	return withHooks(ctx, emc.sqlSave, emc.mutation, emc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (emc *EmployeeMasterCreate) SaveX(ctx context.Context) *EmployeeMaster {
	v, err := emc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (emc *EmployeeMasterCreate) Exec(ctx context.Context) error {
	_, err := emc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (emc *EmployeeMasterCreate) ExecX(ctx context.Context) {
	if err := emc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (emc *EmployeeMasterCreate) defaults() {
	if _, ok := emc.mutation.UpdatedBy(); !ok {
		v := employeemaster.DefaultUpdatedBy
		emc.mutation.SetUpdatedBy(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (emc *EmployeeMasterCreate) check() error {
	if _, ok := emc.mutation.EmployeeID(); !ok {
		return &ValidationError{Name: "EmployeeID", err: errors.New(`ent: missing required field "EmployeeMaster.EmployeeID"`)}
	}
	if _, ok := emc.mutation.Gender(); !ok {
		return &ValidationError{Name: "Gender", err: errors.New(`ent: missing required field "EmployeeMaster.Gender"`)}
	}
	if v, ok := emc.mutation.Gender(); ok {
		if err := employeemaster.GenderValidator(v); err != nil {
			return &ValidationError{Name: "Gender", err: fmt.Errorf(`ent: validator failed for field "EmployeeMaster.Gender": %w`, err)}
		}
	}
	return nil
}

func (emc *EmployeeMasterCreate) sqlSave(ctx context.Context) (*EmployeeMaster, error) {
	if err := emc.check(); err != nil {
		return nil, err
	}
	_node, _spec := emc.createSpec()
	if err := sqlgraph.CreateNode(ctx, emc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	emc.mutation.id = &_node.ID
	emc.mutation.done = true
	return _node, nil
}

func (emc *EmployeeMasterCreate) createSpec() (*EmployeeMaster, *sqlgraph.CreateSpec) {
	var (
		_node = &EmployeeMaster{config: emc.config}
		_spec = sqlgraph.NewCreateSpec(employeemaster.Table, sqlgraph.NewFieldSpec(employeemaster.FieldID, field.TypeInt64))
	)
	if id, ok := emc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := emc.mutation.EmployeeID(); ok {
		_spec.SetField(employeemaster.FieldEmployeeID, field.TypeInt64, value)
		_node.EmployeeID = value
	}
	if value, ok := emc.mutation.EmployeeName(); ok {
		_spec.SetField(employeemaster.FieldEmployeeName, field.TypeString, value)
		_node.EmployeeName = value
	}
	if value, ok := emc.mutation.DOB(); ok {
		_spec.SetField(employeemaster.FieldDOB, field.TypeString, value)
		_node.DOB = value
	}
	if value, ok := emc.mutation.Gender(); ok {
		_spec.SetField(employeemaster.FieldGender, field.TypeEnum, value)
		_node.Gender = value
	}
	if value, ok := emc.mutation.MobileNumber(); ok {
		_spec.SetField(employeemaster.FieldMobileNumber, field.TypeString, value)
		_node.MobileNumber = value
	}
	if value, ok := emc.mutation.EmailID(); ok {
		_spec.SetField(employeemaster.FieldEmailID, field.TypeString, value)
		_node.EmailID = value
	}
	if value, ok := emc.mutation.EmployeeCategoryCode(); ok {
		_spec.SetField(employeemaster.FieldEmployeeCategoryCode, field.TypeString, value)
		_node.EmployeeCategoryCode = value
	}
	if value, ok := emc.mutation.EmployeeCategory(); ok {
		_spec.SetField(employeemaster.FieldEmployeeCategory, field.TypeString, value)
		_node.EmployeeCategory = value
	}
	if value, ok := emc.mutation.PostCode(); ok {
		_spec.SetField(employeemaster.FieldPostCode, field.TypeString, value)
		_node.PostCode = value
	}
	if value, ok := emc.mutation.EmployeePost(); ok {
		_spec.SetField(employeemaster.FieldEmployeePost, field.TypeString, value)
		_node.EmployeePost = value
	}
	if value, ok := emc.mutation.FacilityID(); ok {
		_spec.SetField(employeemaster.FieldFacilityID, field.TypeString, value)
		_node.FacilityID = value
	}
	if value, ok := emc.mutation.DCCS(); ok {
		_spec.SetField(employeemaster.FieldDCCS, field.TypeString, value)
		_node.DCCS = value
	}
	if value, ok := emc.mutation.DCInPresentCadre(); ok {
		_spec.SetField(employeemaster.FieldDCInPresentCadre, field.TypeString, value)
		_node.DCInPresentCadre = value
	}
	if value, ok := emc.mutation.UpdatedAt(); ok {
		_spec.SetField(employeemaster.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := emc.mutation.UpdatedBy(); ok {
		_spec.SetField(employeemaster.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := emc.mutation.Cadre(); ok {
		_spec.SetField(employeemaster.FieldCadre, field.TypeString, value)
		_node.Cadre = value
	}
	if nodes := emc.mutation.UsermasterRefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employeemaster.UsermasterRefTable,
			Columns: []string{employeemaster.UsermasterRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usermaster.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := emc.mutation.EmpRefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employeemaster.EmpRefTable,
			Columns: []string{employeemaster.EmpRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exam_applications_ps.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EmployeeMasterCreateBulk is the builder for creating many EmployeeMaster entities in bulk.
type EmployeeMasterCreateBulk struct {
	config
	builders []*EmployeeMasterCreate
}

// Save creates the EmployeeMaster entities in the database.
func (emcb *EmployeeMasterCreateBulk) Save(ctx context.Context) ([]*EmployeeMaster, error) {
	specs := make([]*sqlgraph.CreateSpec, len(emcb.builders))
	nodes := make([]*EmployeeMaster, len(emcb.builders))
	mutators := make([]Mutator, len(emcb.builders))
	for i := range emcb.builders {
		func(i int, root context.Context) {
			builder := emcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmployeeMasterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, emcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, emcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, emcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (emcb *EmployeeMasterCreateBulk) SaveX(ctx context.Context) []*EmployeeMaster {
	v, err := emcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (emcb *EmployeeMasterCreateBulk) Exec(ctx context.Context) error {
	_, err := emcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (emcb *EmployeeMasterCreateBulk) ExecX(ctx context.Context) {
	if err := emcb.Exec(ctx); err != nil {
		panic(err)
	}
}
