// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"recruit/ent/ageeligibility"
	"recruit/ent/exameligibility"
	"recruit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExamEligibilityQuery is the builder for querying ExamEligibility entities.
type ExamEligibilityQuery struct {
	config
	ctx                  *QueryContext
	order                []exameligibility.OrderOption
	inters               []Interceptor
	predicates           []predicate.ExamEligibility
	withAgeEligibilities *AgeEligibilityQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExamEligibilityQuery builder.
func (eeq *ExamEligibilityQuery) Where(ps ...predicate.ExamEligibility) *ExamEligibilityQuery {
	eeq.predicates = append(eeq.predicates, ps...)
	return eeq
}

// Limit the number of records to be returned by this query.
func (eeq *ExamEligibilityQuery) Limit(limit int) *ExamEligibilityQuery {
	eeq.ctx.Limit = &limit
	return eeq
}

// Offset to start from.
func (eeq *ExamEligibilityQuery) Offset(offset int) *ExamEligibilityQuery {
	eeq.ctx.Offset = &offset
	return eeq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eeq *ExamEligibilityQuery) Unique(unique bool) *ExamEligibilityQuery {
	eeq.ctx.Unique = &unique
	return eeq
}

// Order specifies how the records should be ordered.
func (eeq *ExamEligibilityQuery) Order(o ...exameligibility.OrderOption) *ExamEligibilityQuery {
	eeq.order = append(eeq.order, o...)
	return eeq
}

// QueryAgeEligibilities chains the current query on the "age_eligibilities" edge.
func (eeq *ExamEligibilityQuery) QueryAgeEligibilities() *AgeEligibilityQuery {
	query := (&AgeEligibilityClient{config: eeq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eeq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eeq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(exameligibility.Table, exameligibility.FieldID, selector),
			sqlgraph.To(ageeligibility.Table, ageeligibility.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, exameligibility.AgeEligibilitiesTable, exameligibility.AgeEligibilitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(eeq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ExamEligibility entity from the query.
// Returns a *NotFoundError when no ExamEligibility was found.
func (eeq *ExamEligibilityQuery) First(ctx context.Context) (*ExamEligibility, error) {
	nodes, err := eeq.Limit(1).All(setContextOp(ctx, eeq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{exameligibility.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eeq *ExamEligibilityQuery) FirstX(ctx context.Context) *ExamEligibility {
	node, err := eeq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ExamEligibility ID from the query.
// Returns a *NotFoundError when no ExamEligibility ID was found.
func (eeq *ExamEligibilityQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = eeq.Limit(1).IDs(setContextOp(ctx, eeq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{exameligibility.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eeq *ExamEligibilityQuery) FirstIDX(ctx context.Context) int32 {
	id, err := eeq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ExamEligibility entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ExamEligibility entity is found.
// Returns a *NotFoundError when no ExamEligibility entities are found.
func (eeq *ExamEligibilityQuery) Only(ctx context.Context) (*ExamEligibility, error) {
	nodes, err := eeq.Limit(2).All(setContextOp(ctx, eeq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{exameligibility.Label}
	default:
		return nil, &NotSingularError{exameligibility.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eeq *ExamEligibilityQuery) OnlyX(ctx context.Context) *ExamEligibility {
	node, err := eeq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ExamEligibility ID in the query.
// Returns a *NotSingularError when more than one ExamEligibility ID is found.
// Returns a *NotFoundError when no entities are found.
func (eeq *ExamEligibilityQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = eeq.Limit(2).IDs(setContextOp(ctx, eeq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{exameligibility.Label}
	default:
		err = &NotSingularError{exameligibility.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eeq *ExamEligibilityQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := eeq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ExamEligibilities.
func (eeq *ExamEligibilityQuery) All(ctx context.Context) ([]*ExamEligibility, error) {
	ctx = setContextOp(ctx, eeq.ctx, "All")
	if err := eeq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ExamEligibility, *ExamEligibilityQuery]()
	return withInterceptors[[]*ExamEligibility](ctx, eeq, qr, eeq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eeq *ExamEligibilityQuery) AllX(ctx context.Context) []*ExamEligibility {
	nodes, err := eeq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ExamEligibility IDs.
func (eeq *ExamEligibilityQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if eeq.ctx.Unique == nil && eeq.path != nil {
		eeq.Unique(true)
	}
	ctx = setContextOp(ctx, eeq.ctx, "IDs")
	if err = eeq.Select(exameligibility.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eeq *ExamEligibilityQuery) IDsX(ctx context.Context) []int32 {
	ids, err := eeq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eeq *ExamEligibilityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eeq.ctx, "Count")
	if err := eeq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eeq, querierCount[*ExamEligibilityQuery](), eeq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eeq *ExamEligibilityQuery) CountX(ctx context.Context) int {
	count, err := eeq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eeq *ExamEligibilityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eeq.ctx, "Exist")
	switch _, err := eeq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eeq *ExamEligibilityQuery) ExistX(ctx context.Context) bool {
	exist, err := eeq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExamEligibilityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eeq *ExamEligibilityQuery) Clone() *ExamEligibilityQuery {
	if eeq == nil {
		return nil
	}
	return &ExamEligibilityQuery{
		config:               eeq.config,
		ctx:                  eeq.ctx.Clone(),
		order:                append([]exameligibility.OrderOption{}, eeq.order...),
		inters:               append([]Interceptor{}, eeq.inters...),
		predicates:           append([]predicate.ExamEligibility{}, eeq.predicates...),
		withAgeEligibilities: eeq.withAgeEligibilities.Clone(),
		// clone intermediate query.
		sql:  eeq.sql.Clone(),
		path: eeq.path,
	}
}

// WithAgeEligibilities tells the query-builder to eager-load the nodes that are connected to
// the "age_eligibilities" edge. The optional arguments are used to configure the query builder of the edge.
func (eeq *ExamEligibilityQuery) WithAgeEligibilities(opts ...func(*AgeEligibilityQuery)) *ExamEligibilityQuery {
	query := (&AgeEligibilityClient{config: eeq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eeq.withAgeEligibilities = query
	return eeq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Examcode int32 `json:"Examcode,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ExamEligibility.Query().
//		GroupBy(exameligibility.FieldExamcode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eeq *ExamEligibilityQuery) GroupBy(field string, fields ...string) *ExamEligibilityGroupBy {
	eeq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExamEligibilityGroupBy{build: eeq}
	grbuild.flds = &eeq.ctx.Fields
	grbuild.label = exameligibility.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Examcode int32 `json:"Examcode,omitempty"`
//	}
//
//	client.ExamEligibility.Query().
//		Select(exameligibility.FieldExamcode).
//		Scan(ctx, &v)
func (eeq *ExamEligibilityQuery) Select(fields ...string) *ExamEligibilitySelect {
	eeq.ctx.Fields = append(eeq.ctx.Fields, fields...)
	sbuild := &ExamEligibilitySelect{ExamEligibilityQuery: eeq}
	sbuild.label = exameligibility.Label
	sbuild.flds, sbuild.scan = &eeq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExamEligibilitySelect configured with the given aggregations.
func (eeq *ExamEligibilityQuery) Aggregate(fns ...AggregateFunc) *ExamEligibilitySelect {
	return eeq.Select().Aggregate(fns...)
}

func (eeq *ExamEligibilityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eeq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eeq); err != nil {
				return err
			}
		}
	}
	for _, f := range eeq.ctx.Fields {
		if !exameligibility.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eeq.path != nil {
		prev, err := eeq.path(ctx)
		if err != nil {
			return err
		}
		eeq.sql = prev
	}
	return nil
}

func (eeq *ExamEligibilityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ExamEligibility, error) {
	var (
		nodes       = []*ExamEligibility{}
		_spec       = eeq.querySpec()
		loadedTypes = [1]bool{
			eeq.withAgeEligibilities != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ExamEligibility).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ExamEligibility{config: eeq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eeq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := eeq.withAgeEligibilities; query != nil {
		if err := eeq.loadAgeEligibilities(ctx, query, nodes,
			func(n *ExamEligibility) { n.Edges.AgeEligibilities = []*AgeEligibility{} },
			func(n *ExamEligibility, e *AgeEligibility) {
				n.Edges.AgeEligibilities = append(n.Edges.AgeEligibilities, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (eeq *ExamEligibilityQuery) loadAgeEligibilities(ctx context.Context, query *AgeEligibilityQuery, nodes []*ExamEligibility, init func(*ExamEligibility), assign func(*ExamEligibility, *AgeEligibility)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int32]*ExamEligibility)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ageeligibility.FieldEligibilityCode)
	}
	query.Where(predicate.AgeEligibility(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(exameligibility.AgeEligibilitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.EligibilityCode
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "EligibilityCode" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (eeq *ExamEligibilityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eeq.querySpec()
	_spec.Node.Columns = eeq.ctx.Fields
	if len(eeq.ctx.Fields) > 0 {
		_spec.Unique = eeq.ctx.Unique != nil && *eeq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eeq.driver, _spec)
}

func (eeq *ExamEligibilityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(exameligibility.Table, exameligibility.Columns, sqlgraph.NewFieldSpec(exameligibility.FieldID, field.TypeInt32))
	_spec.From = eeq.sql
	if unique := eeq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eeq.path != nil {
		_spec.Unique = true
	}
	if fields := eeq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exameligibility.FieldID)
		for i := range fields {
			if fields[i] != exameligibility.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eeq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eeq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eeq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eeq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eeq *ExamEligibilityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eeq.driver.Dialect())
	t1 := builder.Table(exameligibility.Table)
	columns := eeq.ctx.Fields
	if len(columns) == 0 {
		columns = exameligibility.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eeq.sql != nil {
		selector = eeq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eeq.ctx.Unique != nil && *eeq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eeq.predicates {
		p(selector)
	}
	for _, p := range eeq.order {
		p(selector)
	}
	if offset := eeq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eeq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExamEligibilityGroupBy is the group-by builder for ExamEligibility entities.
type ExamEligibilityGroupBy struct {
	selector
	build *ExamEligibilityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eegb *ExamEligibilityGroupBy) Aggregate(fns ...AggregateFunc) *ExamEligibilityGroupBy {
	eegb.fns = append(eegb.fns, fns...)
	return eegb
}

// Scan applies the selector query and scans the result into the given value.
func (eegb *ExamEligibilityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eegb.build.ctx, "GroupBy")
	if err := eegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExamEligibilityQuery, *ExamEligibilityGroupBy](ctx, eegb.build, eegb, eegb.build.inters, v)
}

func (eegb *ExamEligibilityGroupBy) sqlScan(ctx context.Context, root *ExamEligibilityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(eegb.fns))
	for _, fn := range eegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*eegb.flds)+len(eegb.fns))
		for _, f := range *eegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*eegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExamEligibilitySelect is the builder for selecting fields of ExamEligibility entities.
type ExamEligibilitySelect struct {
	*ExamEligibilityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ees *ExamEligibilitySelect) Aggregate(fns ...AggregateFunc) *ExamEligibilitySelect {
	ees.fns = append(ees.fns, fns...)
	return ees
}

// Scan applies the selector query and scans the result into the given value.
func (ees *ExamEligibilitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ees.ctx, "Select")
	if err := ees.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExamEligibilityQuery, *ExamEligibilitySelect](ctx, ees.ExamEligibilityQuery, ees, ees.inters, v)
}

func (ees *ExamEligibilitySelect) sqlScan(ctx context.Context, root *ExamEligibilityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ees.fns))
	for _, fn := range ees.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ees.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ees.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
