// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"recruit/ent/exam_pa"
	"recruit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExamPADelete is the builder for deleting a Exam_PA entity.
type ExamPADelete struct {
	config
	hooks    []Hook
	mutation *ExamPAMutation
}

// Where appends a list predicates to the ExamPADelete builder.
func (epd *ExamPADelete) Where(ps ...predicate.Exam_PA) *ExamPADelete {
	epd.mutation.Where(ps...)
	return epd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (epd *ExamPADelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, epd.sqlExec, epd.mutation, epd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (epd *ExamPADelete) ExecX(ctx context.Context) int {
	n, err := epd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (epd *ExamPADelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(exam_pa.Table, sqlgraph.NewFieldSpec(exam_pa.FieldID, field.TypeInt32))
	if ps := epd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, epd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	epd.mutation.done = true
	return affected, err
}

// ExamPADeleteOne is the builder for deleting a single Exam_PA entity.
type ExamPADeleteOne struct {
	epd *ExamPADelete
}

// Where appends a list predicates to the ExamPADelete builder.
func (epdo *ExamPADeleteOne) Where(ps ...predicate.Exam_PA) *ExamPADeleteOne {
	epdo.epd.mutation.Where(ps...)
	return epdo
}

// Exec executes the deletion query.
func (epdo *ExamPADeleteOne) Exec(ctx context.Context) error {
	n, err := epdo.epd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{exam_pa.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (epdo *ExamPADeleteOne) ExecX(ctx context.Context) {
	if err := epdo.Exec(ctx); err != nil {
		panic(err)
	}
}
